name: Docker Image CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/clockbox:latest



#access token : dckr_pat_C7gE7wdpYzcd1yR3_Ob8B2MTglg